spring:
  application:
    name: gestion-inventario

  datasource:
    url: jdbc:mysql://localhost:3306/inventario?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: false      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect 

server:
  port: 8080
